### ISSUE TITLE
Hyperion dont works on 1.20.6 PK version 1.11.3

### ISSUE THREAD

**Issue by Tungdil83** [PrimordialMoros/Hyperion#10]
[08:07:40 WARN]: java.lang.IllegalArgumentException: missing required data class org.bukkit.Color

[08:07:40 WARN]: at com.google.common.base.Preconditions.checkArgument(Preconditions.java:218)

[08:07:40 WARN]: at org.bukkit.craftbukkit.CraftParticle.createParticleParam(CraftParticle.java:68)

[08:07:40 WARN]: at org.bukkit.craftbukkit.CraftWorld.spawnParticle(CraftWorld.java:2262)

[08:07:40 WARN]: at org.bukkit.craftbukkit.CraftWorld.spawnParticle(CraftWorld.java:2250)

[08:07:40 WARN]: at org.bukkit.craftbukkit.CraftWorld.spawnParticle(CraftWorld.java:2244)

[08:07:40 WARN]: at ProjectKorra-1.11.3.jar//com.projectkorra.projectkorra.util.ParticleEffect.display(ParticleEffect.java:150)

[08:07:40 WARN]: at ProjectKorra-1.11.3.jar//com.projectkorra.projectkorra.util.ParticleEffect.display(ParticleEffect.java:178)

[08:07:40 WARN]: at Hyperion-1.7.2.jar//me.moros.hyperion.abilities.waterbending.IceBreath.visualizeBreath(IceBreath.java:152)

[08:07:40 WARN]: at Hyperion-1.7.2.jar//me.moros.hyperion.abilities.waterbending.IceBreath.progress(IceBreath.java:117)

[08:07:40 WARN]: at ProjectKorra-1.11.3.jar//com.projectkorra.projectkorra.ability.CoreAbility.progressAll(CoreAbility.java:277)

[08:07:40 WARN]: at ProjectKorra-1.11.3.jar//com.projectkorra.projectkorra.BendingManager.run(BendingManager.java:113)

[08:07:40 WARN]: at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101)

[08:07:40 WARN]: at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482)

[08:07:40 WARN]: at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1699)

[08:07:40 WARN]: at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:467)

[08:07:40 WARN]: at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1571)

[08:07:40 WARN]: at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1231)

[08:07:40 WARN]: at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)

[08:07:40 WARN]: at java.base/java.lang.Thread.run(Thread.java:1583)

[08:07:40 ERROR]: me.moros.hyperion.abilities.waterbending.IceBreath@1b988829[

line=[Location{world=CraftWorld{name=world},x=254.8205239606971,y=64.29354037848698,z=69.68676754982916,pitch=-5.403066,yaw=77.677826}, Location{world=CraftWorld{name=world},x=254.57736837617415,y=64.31708077604745,z=69.73988262676586,pitch=-5.403066,yaw=77.677826}, Location{world=CraftWorld{name=world},x=254.3342127916512,y=64.34062117360791,z=69.79299770370257,pitch=-5.403066,yaw=77.677826}, Location{world=CraftWorld{name=world},x=254.09105720712824,y=64.36416157116838,z=69.84611278063927,pitch=-5.403066,yaw=77.677826}, Location{world=CraftWorld{name=world},x=253.8479016226053,y=64.38770196872885,z=69.89922785757598,pitch=-5.403066,yaw=77.677826}, Location{world=CraftWorld{name=world},x=253.60474603808234,y=64.41124236628931,z=69.95234293451269,pitch=-5.403066,yaw=77.677826}, Location{world=CraftWorld{name=world},x=253.3615904535594,y=64.43478276384978,z=70.00545801144939,pitch=-5.403066,yaw=77.677826}, Location{world=CraftWorld{name=world},x=253.11843486903643,y=64.45832316141025,z=70.0585730883861,pitch=-5.403066,yaw=77.677826}, Location{world=CraftWorld{name=world},x=252.87527928451348,y=64.48186355897072,z=70.1116881653228,pitch=-5.403066,yaw=77.677826}, Location{world=CraftWorld{name=world},x=252.63212369999053,y=64.50540395653118,z=70.16480324225951,pitch=-5.403066,yaw=77.677826}, Location{world=CraftWorld{name=world},x=252.38896811546758,y=64.52894435409165,z=70.21791831919622,pitch=-5.403066,yaw=77.677826}, Location{world=CraftWorld{name=world},x=252.14581253094462,y=64.55248475165212,z=70.27103339613292,pitch=-5.403066,yaw=77.677826}, Location{world=CraftWorld{name=world},x=251.90265694642167,y=64.57602514921258,z=70.32414847306963,pitch=-5.403066,yaw=77.677826}, Location{world=CraftWorld{name=world},x=251.65950136189872,y=64.59956554677305,z=70.37726355000633,pitch=-5.403066,yaw=77.677826}, Location{world=CraftWorld{name=world},x=251.41634577737577,y=64.62310594433352,z=70.43037862694304,pitch=-5.403066,yaw=77.677826}, Location{world=CraftWorld{name=world},x=251.17319019285281,y=64.64664634189398,z=70.48349370387974,pitch=-5.403066,yaw=77.677826}, Location{world=CraftWorld{name=world},x=250.93003460832986,y=64.67018673945445,z=70.53660878081645,pitch=-5.403066,yaw=77.677826}, Location{world=CraftWorld{name=world},x=250.6868790238069,y=64.69372713701492,z=70.58972385775316,pitch=-5.403066,yaw=77.677826}, Location{world=CraftWorld{name=world},x=250.44372343928396,y=64.71726753457538,z=70.64283893468986,pitch=-5.403066,yaw=77.677826}, Location{world=CraftWorld{name=world},x=250.200567854761,y=64.74080793213585,z=70.69595401162657,pitch=-5.403066,yaw=77.677826}]

location=Location{world=CraftWorld{name=world},x=254.8205239606971,y=64.29354037848698,z=69.68676754982916,pitch=-5.403066,yaw=77.677826}

damage=3.0

range=5

cooldown=10000

chargeTime=1000

frostDuration=5000

currentRange=0.25

charged=true

released=true

player=CraftPlayer{name=Tungdil83}

bPlayer=com.projectkorra.projectkorra.BendingPlayer@1fadd433[

slowTime=0

player=CraftPlayer{name=Tungdil83}

stance=<null>

tremorSense=true

illumination=true

chiBlocked=false

player=CraftPlayer{name=Tungdil83}

uuid=f1dcbeb3-ee5c-4dac-807d-090615dd2bde

permaRemoved=false

toggled=true

allPassivesToggled=true

loading=false

elements=[§bWater]

subelements=[§x§9§9§f§5§f§fIce, §x§3§6§d§2§e§3Healing, §x§a§3§0§0§1§0Blood, §x§0§0§8§0§4§8Plant]

abilities={1=WaterManipulation, 2=Surge, 3=IceBreath, 4=WaterSpout, 5=IceCrawl, 6=PhaseChange, 7=Torrent, 8=WaterBubble, 9=IceBlast}

cooldowns={IceBreath=com.projectkorra.projectkorra.util.Cooldown@40e6f7c}

toggledElements=[]

toggledPassives=[]

currentSlot=0

lastAccessed=1721203121767

uncacheTime=30000

uncache=<null>

]

flightHandler=com.projectkorra.projectkorra.util.FlightHandler@283d38f5

attributeModifiers={}

attributeValues={}

started=true

removed=false

hidden=false

id=-2147483643

startTime=1721203657437

startTick=11146

attributesModified=true

]

**Comment by Tungdil83** [comment]
Thank your for updating Hyperion. This help me so much. 😄
