### ISSUE TITLE
Fail to include plugin (SpigotMC 1.17.1)

### ISSUE THREAD

**Issue by avivlevy37** [PrimordialMoros/Hyperion#6]
[22:35:37] [Server thread/ERROR]: Error occurred while enabling Hyperion v1.6.6 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bstats/bukkit/MetricsLite
	at me.moros.hyperion.Hyperion.onEnable(Hyperion.java:48) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[server.jar:3178-Spigot-eac3cd9-a6292cc]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[server.jar:3178-Spigot-eac3cd9-a6292cc]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[server.jar:3178-Spigot-eac3cd9-a6292cc]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:495) ~[server.jar:3178-Spigot-eac3cd9-a6292cc]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:409) ~[server.jar:3178-Spigot-eac3cd9-a6292cc]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:604) ~[server.jar:3178-Spigot-eac3cd9-a6292cc]
	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:266) ~[server.jar:3178-Spigot-eac3cd9-a6292cc]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:995) ~[server.jar:3178-Spigot-eac3cd9-a6292cc]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303) ~[server.jar:3178-Spigot-eac3cd9-a6292cc]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassNotFoundException: org.bstats.bukkit.MetricsLite
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:142) ~[server.jar:3178-Spigot-eac3cd9-a6292cc]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[server.jar:3178-Spigot-eac3cd9-a6292cc]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	... 11 more

**Comment by PrimordialMoros** [comment]
Did you build the jar yourself?
